import vine from '@vinejs/vine'

/**
 * Validator to validate the payload when creating
 * a new reservation room.
 */
export const createReservationRoomValidator = vine.compile(
  vine.object({
    reservationId: vine.number().positive(),
    roomId: vine.number().positive(),
    roomTypeId: vine.number().positive(),
    checkInDate: vine.date(),
    checkOutDate: vine.date(),
    expectedCheckInTime: vine.date().optional(),
    expectedCheckOutTime: vine.date().optional(),
    adults: vine.number().min(1).max(10),
    children: vine.number().min(0).max(10),
    infants: vine.number().min(0).max(5),
    nights: vine.number().min(1),
    baseRate: vine.number().min(0),
    roomCharges: vine.number().min(0).optional(),
    taxAmount: vine.number().min(0).optional(),
    discountAmount: vine.number().min(0).optional(),
    totalAmount: vine.number().min(0),
    currency: vine.string().fixedLength(3).optional(),
    ratePlanCode: vine.string().maxLength(50).optional(),
    packageCode: vine.string().maxLength(50).optional(),
    marketSegment: vine.string().maxLength(50).optional(),
    sourceCode: vine.string().maxLength(50).optional(),
    guestType: vine.enum(['individual', 'group', 'corporate', 'government', 'travel_agent', 'online', 'walk_in']).optional(),
    vipStatus: vine.enum(['none', 'bronze', 'silver', 'gold', 'platinum', 'diamond']).optional(),
    loyaltyNumber: vine.string().maxLength(50).optional(),
    specialRequests: vine.string().maxLength(1000).optional(),
    guestPreferences: vine.string().maxLength(1000).optional(),
    dietaryRestrictions: vine.string().maxLength(500).optional(),
    accessibilityNeeds: vine.string().maxLength(500).optional(),
    bedType: vine.enum(['single', 'double', 'queen', 'king', 'twin', 'sofa_bed', 'murphy_bed', 'bunk_bed']).optional(),
    smokingPreference: vine.enum(['non_smoking', 'smoking', 'no_preference']).optional(),
    floorPreference: vine.enum(['low', 'high', 'specific', 'no_preference']).optional(),
    viewPreference: vine.enum(['ocean', 'city', 'garden', 'pool', 'mountain', 'courtyard', 'no_preference']).optional(),
    roomLocation: vine.enum(['near_elevator', 'away_from_elevator', 'near_stairs', 'away_from_stairs', 'quiet_area', 'no_preference']).optional(),
    connectingRooms: vine.boolean().optional(),
    earlyCheckIn: vine.boolean().optional(),
    lateCheckOut: vine.boolean().optional(),
    airportTransfer: vine.boolean().optional(),
    extraBed: vine.boolean().optional(),
    crib: vine.boolean().optional(),
    rollawayBed: vine.boolean().optional(),
    welcomeGift: vine.boolean().optional(),
    roomDecoration: vine.boolean().optional(),
    champagne: vine.boolean().optional(),
    flowers: vine.boolean().optional(),
    chocolates: vine.boolean().optional(),
    fruitBasket: vine.boolean().optional(),
    newspaperDelivery: vine.boolean().optional(),
    wakeUpCall: vine.boolean().optional(),
    doNotDisturb: vine.boolean().optional(),
    expressCheckOut: vine.boolean().optional(),
    digitalKey: vine.boolean().optional(),
    mobileCheckIn: vine.boolean().optional(),
    status: vine.enum(['reserved', 'checked_in', 'checked_out', 'no_show', 'cancelled', 'blocked']).optional(),
    checkInStatus: vine.enum(['pending', 'checked_in', 'no_show', 'cancelled']).optional(),
    checkOutStatus: vine.enum(['pending', 'checked_out', 'extended', 'early']).optional(),
    keyCardsIssued: vine.number().min(0).max(10).optional(),
    keyCardsReturned: vine.number().min(0).max(10).optional(),
    depositAmount: vine.number().min(0).optional(),
    incidentalCharges: vine.number().min(0).optional(),
    damageCharges: vine.number().min(0).optional(),
    minibarCharges: vine.number().min(0).optional(),
    phoneCharges: vine.number().min(0).optional(),
    internetCharges: vine.number().min(0).optional(),
    laundryCharges: vine.number().min(0).optional(),
    spaCharges: vine.number().min(0).optional(),
    restaurantCharges: vine.number().min(0).optional(),
    roomServiceCharges: vine.number().min(0).optional(),
    parkingCharges: vine.number().min(0).optional(),
    businessCenterCharges: vine.number().min(0).optional(),
    otherCharges: vine.number().min(0).optional(),
    totalCharges: vine.number().min(0).optional(),
    checkInNotes: vine.string().maxLength(1000).optional(),
    checkOutNotes: vine.string().maxLength(1000).optional(),
    housekeepingNotes: vine.string().maxLength(1000).optional(),
    maintenanceNotes: vine.string().maxLength(1000).optional(),
    securityNotes: vine.string().maxLength(1000).optional(),
    guestServiceNotes: vine.string().maxLength(1000).optional(),
    billingNotes: vine.string().maxLength(1000).optional(),
    internalNotes: vine.string().maxLength(1000).optional(),
    notes: vine.string().maxLength(1000).optional(),
    rateAmount: vine.number().min(0).optional(),
    roomChangeReason: vine.string().maxLength(500).optional(),
    roomChangedAt: vine.date().optional(),
    roomChangedBy: vine.number().positive().optional(),
    upgradeReason: vine.string().maxLength(500).optional(),
    upgradedAt: vine.date().optional(),
    upgradedBy: vine.number().positive().optional(),
    downgradeReason: vine.string().maxLength(500).optional(),
    downgradedAt: vine.date().optional(),
    downgradedBy: vine.number().positive().optional(),
    extensionReason: vine.string().maxLength(500).optional(),
    extendedUntil: vine.date().optional(),
    extendedBy: vine.number().positive().optional(),
    earlyCheckOutReason: vine.string().maxLength(500).optional(),
    earlyCheckOutAt: vine.date().optional(),
    earlyCheckOutBy: vine.number().positive().optional(),
    noShowReason: vine.string().maxLength(500).optional(),
    noShowAt: vine.date().optional(),
    noShowBy: vine.number().positive().optional(),
    cancellationReason: vine.string().maxLength(500).optional(),
    cancelledAt: vine.date().optional(),
    cancelledBy: vine.number().positive().optional(),
    compReason: vine.string().maxLength(500).optional(),
    compAuthorizedBy: vine.number().positive().optional(),
    compAmount: vine.number().min(0).optional(),
    discountReason: vine.string().maxLength(500).optional(),
    discountAuthorizedBy: vine.number().positive().optional(),
    upsellOffered: vine.boolean().optional(),
    upsellAccepted: vine.boolean().optional(),
    upsellAmount: vine.number().min(0).optional(),
    crossSellOffered: vine.boolean().optional(),
    crossSellAccepted: vine.boolean().optional(),
    crossSellAmount: vine.number().min(0).optional(),
    loyaltyPointsEarned: vine.number().min(0).optional(),
    loyaltyPointsRedeemed: vine.number().min(0).optional(),
    membershipTier: vine.string().maxLength(50).optional(),
    membershipBenefits: vine.string().maxLength(1000).optional(),
    corporateRate: vine.boolean().optional(),
    corporateCode: vine.string().maxLength(50).optional(),
    groupRate: vine.boolean().optional(),
    groupCode: vine.string().maxLength(50).optional(),
    promotionalRate: vine.boolean().optional(),
    promotionalCode: vine.string().maxLength(50).optional(),
    packageRate: vine.boolean().optional(),
    packageInclusions: vine.string().maxLength(1000).optional(),
    mealPlan: vine.enum(['room_only', 'breakfast', 'half_board', 'full_board', 'all_inclusive']).optional(),
    breakfastIncluded: vine.boolean().optional(),
    lunchIncluded: vine.boolean().optional(),
    dinnerIncluded: vine.boolean().optional(),
    drinksIncluded: vine.boolean().optional(),
    wifiIncluded: vine.boolean().optional(),
    parkingIncluded: vine.boolean().optional(),
    airportTransferIncluded: vine.boolean().optional(),
    spaAccessIncluded: vine.boolean().optional(),
    gymAccessIncluded: vine.boolean().optional(),
    poolAccessIncluded: vine.boolean().optional(),
    businessCenterIncluded: vine.boolean().optional(),
    conciergeServiceIncluded: vine.boolean().optional(),
    roomServiceIncluded: vine.boolean().optional(),
    laundryServiceIncluded: vine.boolean().optional(),
    turndownServiceIncluded: vine.boolean().optional(),
    dailyHousekeepingIncluded: vine.boolean().optional(),
    actualCheckInTime: vine.date().optional(),
    actualCheckOutTime: vine.date().optional(),
    checkedInBy: vine.number().positive().optional(),
    checkedOutBy: vine.number().positive().optional(),
    lastModifiedBy: vine.number().positive().optional(),
    voidedDate: vine.date().optional(),
    voidReason: vine.string().maxLength(500).optional(),
    voidNotes: vine.string().maxLength(1000).optional()
  })
)

/**
 * Validator to validate the payload when updating
 * an existing reservation room.
 */
export const updateReservationRoomValidator = vine.compile(
  vine.object({
    reservationId: vine.number().positive().optional(),
    roomId: vine.number().positive().optional(),
    roomTypeId: vine.number().positive().optional(),
    checkInDate: vine.date().optional(),
    checkOutDate: vine.date().optional(),
    expectedCheckInTime: vine.date().optional(),
    expectedCheckOutTime: vine.date().optional(),
    actualCheckInTime: vine.date().optional(),
    actualCheckOutTime: vine.date().optional(),
    adults: vine.number().min(1).max(10).optional(),
    children: vine.number().min(0).max(10).optional(),
    infants: vine.number().min(0).max(5).optional(),
    nights: vine.number().min(1).optional(),
    baseRate: vine.number().min(0).optional(),
    roomCharges: vine.number().min(0).optional(),
    taxAmount: vine.number().min(0).optional(),
    discountAmount: vine.number().min(0).optional(),
    totalAmount: vine.number().min(0).optional(),
    currency: vine.string().fixedLength(3).optional(),
    ratePlanCode: vine.string().maxLength(50).optional(),
    packageCode: vine.string().maxLength(50).optional(),
    marketSegment: vine.string().maxLength(50).optional(),
    sourceCode: vine.string().maxLength(50).optional(),
    guestType: vine.enum(['individual', 'group', 'corporate', 'government', 'travel_agent', 'online', 'walk_in']).optional(),
    vipStatus: vine.enum(['none', 'bronze', 'silver', 'gold', 'platinum', 'diamond']).optional(),
    loyaltyNumber: vine.string().maxLength(50).optional(),
    specialRequests: vine.string().maxLength(1000).optional(),
    guestPreferences: vine.string().maxLength(1000).optional(),
    dietaryRestrictions: vine.string().maxLength(500).optional(),
    accessibilityNeeds: vine.string().maxLength(500).optional(),
    bedType: vine.enum(['single', 'double', 'queen', 'king', 'twin', 'sofa_bed', 'murphy_bed', 'bunk_bed']).optional(),
    smokingPreference: vine.enum(['non_smoking', 'smoking', 'no_preference']).optional(),
    floorPreference: vine.enum(['low', 'high', 'specific', 'no_preference']).optional(),
    viewPreference: vine.enum(['ocean', 'city', 'garden', 'pool', 'mountain', 'courtyard', 'no_preference']).optional(),
    roomLocation: vine.enum(['near_elevator', 'away_from_elevator', 'near_stairs', 'away_from_stairs', 'quiet_area', 'no_preference']).optional(),
    connectingRooms: vine.boolean().optional(),
    earlyCheckIn: vine.boolean().optional(),
    lateCheckOut: vine.boolean().optional(),
    airportTransfer: vine.boolean().optional(),
    extraBed: vine.boolean().optional(),
    crib: vine.boolean().optional(),
    rollawayBed: vine.boolean().optional(),
    welcomeGift: vine.boolean().optional(),
    roomDecoration: vine.boolean().optional(),
    champagne: vine.boolean().optional(),
    flowers: vine.boolean().optional(),
    chocolates: vine.boolean().optional(),
    fruitBasket: vine.boolean().optional(),
    newspaperDelivery: vine.boolean().optional(),
    wakeUpCall: vine.boolean().optional(),
    doNotDisturb: vine.boolean().optional(),
    expressCheckOut: vine.boolean().optional(),
    digitalKey: vine.boolean().optional(),
    mobileCheckIn: vine.boolean().optional(),
    status: vine.enum(['reserved', 'checked_in', 'checked_out', 'no_show', 'cancelled', 'blocked']).optional(),
    checkInStatus: vine.enum(['pending', 'checked_in', 'no_show', 'cancelled']).optional(),
    checkOutStatus: vine.enum(['pending', 'checked_out', 'extended', 'early']).optional(),
    keyCardsIssued: vine.number().min(0).max(10).optional(),
    keyCardsReturned: vine.number().min(0).max(10).optional(),
    depositAmount: vine.number().min(0).optional(),
    incidentalCharges: vine.number().min(0).optional(),
    damageCharges: vine.number().min(0).optional(),
    minibarCharges: vine.number().min(0).optional(),
    phoneCharges: vine.number().min(0).optional(),
    internetCharges: vine.number().min(0).optional(),
    laundryCharges: vine.number().min(0).optional(),
    spaCharges: vine.number().min(0).optional(),
    restaurantCharges: vine.number().min(0).optional(),
    roomServiceCharges: vine.number().min(0).optional(),
    parkingCharges: vine.number().min(0).optional(),
    businessCenterCharges: vine.number().min(0).optional(),
    otherCharges: vine.number().min(0).optional(),
    totalCharges: vine.number().min(0).optional(),
    checkInNotes: vine.string().maxLength(1000).optional(),
    checkOutNotes: vine.string().maxLength(1000).optional(),
    housekeepingNotes: vine.string().maxLength(1000).optional(),
    maintenanceNotes: vine.string().maxLength(1000).optional(),
    securityNotes: vine.string().maxLength(1000).optional(),
    guestServiceNotes: vine.string().maxLength(1000).optional(),
    billingNotes: vine.string().maxLength(1000).optional(),
    internalNotes: vine.string().maxLength(1000).optional(),
    notes: vine.string().maxLength(1000).optional(),
    rateAmount: vine.number().min(0).optional(),
    roomChangeReason: vine.string().maxLength(500).optional(),
    roomChangedAt: vine.date().optional(),
    roomChangedBy: vine.number().positive().optional(),
    upgradeReason: vine.string().maxLength(500).optional(),
    upgradedAt: vine.date().optional(),
    upgradedBy: vine.number().positive().optional(),
    downgradeReason: vine.string().maxLength(500).optional(),
    downgradedAt: vine.date().optional(),
    downgradedBy: vine.number().positive().optional(),
    extensionReason: vine.string().maxLength(500).optional(),
    extendedUntil: vine.date().optional(),
    extendedBy: vine.number().positive().optional(),
    earlyCheckOutReason: vine.string().maxLength(500).optional(),
    earlyCheckOutAt: vine.date().optional(),
    earlyCheckOutBy: vine.number().positive().optional(),
    noShowReason: vine.string().maxLength(500).optional(),
    noShowAt: vine.date().optional(),
    noShowBy: vine.number().positive().optional(),
    cancellationReason: vine.string().maxLength(500).optional(),
    cancelledAt: vine.date().optional(),
    cancelledBy: vine.number().positive().optional(),
    compReason: vine.string().maxLength(500).optional(),
    compAuthorizedBy: vine.number().positive().optional(),
    compAmount: vine.number().min(0).optional(),
    discountReason: vine.string().maxLength(500).optional(),
    discountAuthorizedBy: vine.number().positive().optional(),
    upsellOffered: vine.boolean().optional(),
    upsellAccepted: vine.boolean().optional(),
    upsellAmount: vine.number().min(0).optional(),
    crossSellOffered: vine.boolean().optional(),
    crossSellAccepted: vine.boolean().optional(),
    crossSellAmount: vine.number().min(0).optional(),
    loyaltyPointsEarned: vine.number().min(0).optional(),
    loyaltyPointsRedeemed: vine.number().min(0).optional(),
    membershipTier: vine.string().maxLength(50).optional(),
    membershipBenefits: vine.string().maxLength(1000).optional(),
    corporateRate: vine.boolean().optional(),
    corporateCode: vine.string().maxLength(50).optional(),
    groupRate: vine.boolean().optional(),
    groupCode: vine.string().maxLength(50).optional(),
    promotionalRate: vine.boolean().optional(),
    promotionalCode: vine.string().maxLength(50).optional(),
    packageRate: vine.boolean().optional(),
    packageInclusions: vine.string().maxLength(1000).optional(),
    mealPlan: vine.enum(['room_only', 'breakfast', 'half_board', 'full_board', 'all_inclusive']).optional(),
    breakfastIncluded: vine.boolean().optional(),
    lunchIncluded: vine.boolean().optional(),
    dinnerIncluded: vine.boolean().optional(),
    drinksIncluded: vine.boolean().optional(),
    wifiIncluded: vine.boolean().optional(),
    parkingIncluded: vine.boolean().optional(),
    airportTransferIncluded: vine.boolean().optional(),
    spaAccessIncluded: vine.boolean().optional(),
    gymAccessIncluded: vine.boolean().optional(),
    poolAccessIncluded: vine.boolean().optional(),
    businessCenterIncluded: vine.boolean().optional(),
    conciergeServiceIncluded: vine.boolean().optional(),
    roomServiceIncluded: vine.boolean().optional(),
    laundryServiceIncluded: vine.boolean().optional(),
    turndownServiceIncluded: vine.boolean().optional(),
    dailyHousekeepingIncluded: vine.boolean().optional(),
    checkedInBy: vine.number().positive().optional(),
    checkedOutBy: vine.number().positive().optional(),
    lastModifiedBy: vine.number().positive().optional(),
    voidedDate: vine.date().optional(),
    voidReason: vine.string().maxLength(500).optional(),
    voidNotes: vine.string().maxLength(1000).optional()
  })
)